apiVersion: v2
name: kubeexecutor
description: ColonyOS executor for k8s
type: application
version: 0.0.3
appVersion: 1.0.9
home: https://colonyos.io/
sources:
  - https://github.com/colonyos/executors/tree/main/kube
  - https://github.com/colonyos/colonies
keywords:
  - Meta-OS
  - Computing Continuum
  - Distributed Computing
maintainers:
  - name: Josef Vilestad
    email: josef.vilestad@ri.se
  - name: Johan Kristiansson
    email: johan.kristiansson@ltu.se
icon: https://github.com/colonyos/colonies/blob/main/docs/images/ColonyOsLogoNoShaddow2.png
annotations:
  functions: execute
