apiVersion: v2
name: colonies
description: Chart to deploy a colony server with a database and monitoring.
type: application
version: 0.0.4
appVersion: 1.9.8
home: https://colonyos.io/
sources:
  - https://github.com/colonyos/helm/tree/main/charts/colonies
  - https://github.com/colonyos/colonies
keywords:
  - Meta-OS
  - Computing Continuum
  - Distributed Computing
maintainers:
  - name: Josef Vilestad
    email: josef.vilestad@ri.se
  - name: Johan Kristiansson
    email: johan.kristiansson@ltu.se
icon: https://github.com/colonyos/colonies/blob/main/docs/images/ColonyOsLogoNoShaddow2.png
